examples/trackers/create/create_tracker.go
examples/trackers/retrieve/retrieve_tracker.go
examples/trackers/retrieve_all/retrieve_trackers.go

Adds tracker examples, answers the question posted in #21 .
Closes #21

Add Tracker Examples

---

CHANGELOG.md
version.go

* Version bump to v1.3.0 for Smartrate
* Makes CHANGELOG markdown

Version bump to v1.3.0 for Smartrate

---

user.go

Add **retrieveMe()** helper method in the User class, the users can call this method to grab their profile. E2E local test was done for this PR.

add retrieveMe() method in the User class.

---

CHANGELOG.md
brand.go
examples/users/update_brand.go
user.go

Added support for updating the user brand in the Golang library, updated the changelog, and fixed a typo.
This is one of the missing core features.
Added methods for updating the user brand and add a new file for a code example. Add a new class for Brand.
E2E local testing, no unit test was written because there is my personal information in the cassette.

Update user brand

---

CHANGELOG.md
UPGRADE_GUIDE.md

Adds an upgrade guide to the project.

chore: adds upgrade guide

---

CHANGELOG.md
batch.go
brand.go
tests/batch_test.go
tests/cassettes/TestBatchAll.yaml
tests/user_test.go

Add `ID` attribute to the `Brand` struct. 
Fix a typo in the `Batch` file, the type of `ListBatchesResult` should be `batch` instead of `insurance`.

fix typo in Batch and add ID attribute for Brand struct.

---

CHANGELOG.md
version.go

chore: prepare v2.1.0 for release

---

CHANGELOG.md
address.go
tests/address_test.go
tests/cassettes/TestAddressCreateAndVerify.yaml

Add missing `CreateAndVerifyAddress` and `CreateAndVerifyAddressWithContext` functions in Address file
Add missing `message` attribute in Address struct
Add missing `Verifications` in `IncorrectAddressToVerify()` reusable function

add create_and_verify endpoint functions in Address.

---

CHANGELOG.md
version.go

chore: prepare v2.2.0 for release

---

tests/cassettes/TestShipmentCreateEmptyObjects.yaml
tests/shipment_test.go

This PR adds a missing assertion for `tax_identifiers`

assertion for tax_identifiers.

---

CHANGELOG.md
README.md

Adds missing upgrade guide link to README and CHANGELOG

docs: add missing upgrade guide link

---

CHANGELOG.md
credit_card.go
payment_method.go
tests/cassettes/TestCreditCardFundWithInvalidInput.yaml
tests/cassettes/TestPaymentMethodsAll.yaml
tests/credit_card_test.go
tests/payment_methods_test.go

Adds `PaymentMethod.ListPaymentMethods()`, `CreditCard.FundCreditCard()`, and `CreditCard.DeleteCreditCard()` functions
Added unit test for retrieving all payment methods
Can't test `CreditCard.FundCreditCard` and `CreditCard.DeleteCreditCard due` to lack of an available real credit card in tests

add billing functions.

---

CHANGELOG.md
carrier.go
rate.go
tests/cassettes/TestPickupBuy.yaml
tests/cassettes/TestPickupCancel.yaml
tests/cassettes/TestPickupCreate.yaml
tests/cassettes/TestPickupRetrieve.yaml
tests/cassettes/TestShipmentBuy.yaml
tests/fixture_test.go

Add `billing_type` in CarrierAccount and Rate structs

add BillingType in CarrierAccount and Rate structs.

---

rate.go

Add missing `billing_type` to smart rate struct

add billing_type in smart rate struct.

---

tests/batch_test.go
tests/cassettes/TestBatchAddRemoveShipment.yaml
tests/cassettes/TestBatchAll.yaml
tests/cassettes/TestBatchBuy.yaml
tests/cassettes/TestBatchCreate.yaml
tests/cassettes/TestBatchCreateAndBuy.yaml
tests/cassettes/TestBatchCreateScanForm.yaml
tests/cassettes/TestBatchLabel.yaml
tests/cassettes/TestBatchRetrieve.yaml

We were for whatever reason sending `nil` shipment data to batch tests and isn't needed. Cleaning that up.

chore: removes nil shipments in batch tests

---

address.go
api_key.go
batch.go
carrier.go
customs.go
event.go
insurance.go
order.go
parcel.go
pickup.go
rate.go
refund.go
report.go
scan_form.go
shipment.go
tracker.go
user.go
webhook.go

Changed the withContext functions in the go library so it can be covered by the tests.

Updated withContext functions.

---

.gitattributes
tests/cassettes/TestAddressAll.yaml

Ignore cassette diffs locally (line 1) and collapse on GitHub (line 2) for easier review.

chore: ignore cassette diffs

---

CHANGELOG.md
client.go

Adds OS specific details to the User-Agent string.

feat: add OS specific details to User-Agent header

---

CHANGELOG.md
version.go

chore: prepare v2.5.0

---

.gitignore

chore: ignore env

---

CHANGELOG.md
carbon_offset.go
rate.go
shipment.go
tests/carbon_offset_test.go
tests/cassettes/TestShipmentBuyWithCarbonOffset.yaml
tests/cassettes/TestShipmentCreateWithCarbonOffset.yaml
tests/cassettes/TestShipmentOneCallBuyWithCarbonOffset.yaml
tests/cassettes/TestShipmentReRateWithCarbonOffset.yaml
tests/cassettes/TestShipmentRegenerateRates.yaml
tests/fixture_test.go

- New functions to create, buy and re-rate a shipment with a carbon offset
- New unit tests
- Fix function using deprecated function
- New unit tests

Carbon offset support

---

CHANGELOG.md
version.go

chore: prepare v2.6.0 for release

---

.github/workflows/ci.yml

Adds Go 1.19 to the test matrix to ensure compatibility.

chore: add Go 1.19 to CI

---

Makefile
README.md

Changes `gosec` to `scan` to be consistent with other libs.
Also adds a `release` target to easily release in the future.

chore: unified Makefile targets

---

shipment.go
shipment_options.go

- Add duty_payment and duty_payment_account to shipment options
- Move shipment options to its own file
- No changes to unit tests

Add duty_payment options

---

CHANGELOG.md
endshipper.go
tests/cassettes/TestEndShipperAll.yaml
tests/cassettes/TestEndShipperCreate.yaml
tests/cassettes/TestEndShipperRetrieve.yaml
tests/cassettes/TestEndShipperUpdate.yaml
tests/endshipper_test.go

Adds the new `EndShipper` beta class with create, retrieve, all, and update functions. This is the fully-qualified address object that the USPS will start requiring shortly.
Add unit tests and pass them

Add EndShipper

---

CHANGELOG.md
version.go

chore: prepares v2.7.0 for release

---

CHANGELOG.md
shipment_options.go

Adds the `EndShipperID` shipment option

feat: adds EndShipperID shipment option

---

carrier.go
event.go
scan_form.go
shipment.go
tests/bootstrap_test.go
tests/carrier_account_test.go
tests/cassettes/TestCarrierAccountUpdate.yaml
tests/cassettes/TestEventRetrievePayload.yaml
tests/cassettes/TestShipmentLowestRateDeprecated.yaml
tests/cassettes/TestWebhookCreateDeprecated.yaml
tests/cassettes/TestWebhookEnableDeprecated.yaml
tests/cassettes/TestWebhookUpdateDeprecated.yaml
tests/client_test.go
tests/event_test.go
tests/shipment_test.go
tests/util_test.go
tests/webhook_test.go
util.go
webhook.go

- Tests everything in the lib that makes sense (all API calls, branches, deprecated functions, errors, etc) and takes coverage from ~70% to ~80%
- Fixed VCR matching error for updating a carrier account
- Enforces 80% test coverage which is what the lib is sitting at now so we can't regress
- TODO: scrub nested lists and dictionaries which will be done when Partner White Label gets added
- Fixes tests as necessary

tests: better test coverage

---

CHANGELOG.md
version.go

chore: prepare v2.8.0 for release

---

.github/workflows/ci.yml
README.md

Adds coveralls support for coverage reporting

feat: add coveralls

---

README.md

Fixes the Godoc link (fixes #130)
Clicked the link.

fix: godoc link (closes #130)

---

shipment_options.go

Added the USPS specific option label_size to ShipmentOptions

Add LabelSize to ShipmentOptions

---

CHANGELOG.md
version.go

chore: prepare v2.9.0 for release

---

.github/workflows/ci.yml
Makefile
README.md
tests/bootstrap_test.go
tests/cassettes/TestApiKeysAll.yaml

Expires cassettes after 180 days
A/B tested by setting a low number with it logging out and a high number with it not

feat: expires cassettes after 180 days

---

CHANGELOG.md
version.go

chore: prepare v2.10.0 for release

---

CHANGELOG.md
shipment_options.go
version.go

chore: prepare v2.11.0 for release

---

version.go

chore: prepare v2.11.1 for release

---

tests/cassettes/TestBuyShipmentWithEndShipper.yaml
tests/shipment_test.go

- Enable "buy shipment with end shipper" unit test
- Unit test enabled, updated, cassette recorded

Enable skipped EndShipper test

---

CHANGELOG.md
pickup.go
tests/cassettes/TestPickupAll.yaml
tests/pickup_test.go

add retrieve pickups function
new test

add retreive pickups function

---

CHANGELOG.md
event.go
tests/cassettes/TestEventRetrieveAllPayloads.yaml
tests/cassettes/TestEventRetrievePayload.yaml
tests/event_test.go

- New function, unit test, cassette to retrieve a specific payload for a specific event
- Improve unit test, cassette for existing function to retrieve all payloads for a specific event
- New and improved unit tests, cassettes

feat: Add functions to retrieve event payload(s)

---

CHANGELOG.md
version.go

chore: prepare v2.12.0 for release

---

README.md

fix: lib doc wording

---

tests/cassettes/TestRefundCreate.yaml
tests/refund_test.go

Fixes the test for creating a refund to send a list instead of a string

fix: refund test

---

CHANGELOG.md
rate.go
shipment.go
tests/cassettes/TestBetaStatelessRateGetLowest.yaml
tests/cassettes/TestBetaStatelessRateGetLowestError.yaml
tests/cassettes/TestBetaStatelessRateRetrieve.yaml
tests/rate_test.go
util.go

- Add beta stateless rate generation, filtering functions
- Add new unit tests, cassettes for beta stateless rate features

[feat] Add beta stateless rating support

---

tracker.go

This input parameter is invalid and was erroneously added. 

(chore) rm invalid param

---

README.md

chore: add support policy

---

CHANGELOG.md
version.go

chore: prepare v2.13.1 for release

---

CHANGELOG.md
version.go

chore: prepare v2.14.0 for release

---

CHANGELOG.md
version.go

chore: prepare v2.16.0 for release

---

CHANGELOG.md
shipment_options.go
version.go

- Adds `SuppressETD` to `ShipmentOptions`
Closes #171

feat: adds SuppressETD to ShipmentOptions (closes #171)

---

CHANGELOG.md
shipment.go
tests/cassettes/TestShipmentGetShipmentEstimatedDeliveryDate.yaml
tests/fixture_test.go
tests/shipment_test.go

Adds `GetShipmentEstimatedDeliveryDate` function
Adds test

feat: adds GetShipmentEstimatedDeliveryDate

---

CHANGELOG.md
version.go

chore: prepare v2.18.0 for release

---

CHANGELOG.md
version.go

chore: prepare v2.19.0 for release

---

.github/workflows/ci.yml
Makefile
README.md

fix: lint target

---

.github/workflows/ci.yml

fix: coveralls on build

---

CHANGELOG.md
version.go

chore: prepare v2.20.0 for release

---

CHANGELOG.md
UPGRADE_GUIDE.md

Upgrade guide and changelog for v3 release, documenting major and minor changes

[chore] Changelog and upgrade guide for v3

---

CHANGELOG.md
version.go

[chore] Prep release

---

CHANGELOG.md
version.go

chore: prepare v3.2.0 for release

---

CHANGELOG.md
referral_customer.go
tests/cassettes/TestUserAllChildUsers.yaml
tests/cassettes/TestUserGetNextChildUserPage.yaml
tests/user_test.go
user.go

- Add `ListChildUsers` and `GetNextChildUserPage` functions to `User` service
- Fix a bad docstring
- Add appropriate unit tests, cassettes

[feat] Add paginated children (beta)

---

CHANGELOG.md
version.go

- Bump version number
- Update changelog

[chore] Prep for v4.1.0 release

---

CHANGELOG.md
version.go

[chore] Prep for v4.1.1. releaseBump version number

---

CHANGELOG.md
insurance.go
tests/cassettes/TestInsuranceRefund.yaml
tests/insurance_test.go

Add `RefundInsurance` function in the insurance service
Added a new unit test

Add RefundInsurance function in insurance service

---

CHANGELOG.md
version.go

Prep release v4.2.0

---

CHANGELOG.md
version.go

chore: prep v4.3.0 for release

---

.github/workflows/ci.yml

[chore] Add Go 1.22 to CI

---

CHANGELOG.md
version.go

Update CHANGELOG and bump version number

[chore] Prep for 4.3.1 release

---

CHANGELOG.md
version.go

[chore] Prep for v4.4.0 release

---

CHANGELOG.md
version.go

- Bump version number
- Update CHANGELOG

[chore] Prep for v4.5.0 release

---

CHANGELOG.md
list_options.go
tests/cassettes/TestUserGetNextChildUserPage.yaml
user.go

Pagination for listing child users needs to use "after_id", not "before_id"

[bug] Fix child user pagination parameters

---

CHANGELOG.md
version.go

[chore] Prep for v4.5.1 release

---

CHANGELOG.md
version.go

While this is a bug fix, the fix itself is significant enough from a risk perspective to warrant a minor version bump.

[chore] Prep for v4.6.0 release

---

CHANGELOG.md
payment_method.go
referral_customer.go
tests/cassettes/TestAddReferralCustomerBankAccountFromStripe.yaml
tests/cassettes/TestAddReferralCustomerCreditCardFromStripe.yaml
tests/cassettes/TestBetaCreateBankAccountClientSecret.yaml
tests/cassettes/TestBetaCreateCreditCardClientSecret.yaml
tests/event_test.go
tests/fixture_test.go
tests/referral_customer_test.go
tests/webhook_test.go
webhook.go

- Adds the following functions to assist ReferralCustomers add credit cards and bank accounts:
- `AddReferralCustomerCreditCardFromStripe`
- `AddReferralCustomerBankAccountFromStripe`
- `BetaCreateCreditCardClientSecret`
- `BetaCreateBankAccountClientSecret`
- `BetaCreateBankAccountClientSecretWithReturlUrl`
- Renames `CreateWebhookWithDetails` to `CreateWebhook` (was previously renamed in the last major version, should not have been based on convention)
- Adds new tests for functions

feat: add new referral customer billing functions

---

CHANGELOG.md
carrier.go
constants.go
tests/carrier_account_test.go
tests/cassettes/TestCarrierAccountCreateOauth.yaml

feat: route Amazon create to correct endpoint

---

CHANGELOG.md
tracker.go

feat: adds EstDeliveryDate to TrackerDetail

---

CHANGELOG.md
version.go

chore: prepare v5.2.0 for release
