carrier.go

The CarrierAccount.Fields field did not have a `json` struct tag. This caused JSON to serialize it using the key "Fields" (capitalized), and it would include it even if it was nil.
This change simply adds the appropriate struct tag so that the correct key will be used, and also so that we don't serialize the field to JSON if it is empty.

Add JSON Struct Tag to CarrierAccount.Fields

---

shipment.go

The _CreateShipment_ method supports an optional carrier account ID parameter. If specified along with providing a service on the shipment object, shipments can be created and bought with one request.
Previously, we were not sending the optional carrier account parameter in the right way, which caused the API to return an error. This change fixes that bug.
I re-ran existing automated tests and made sure they pass. I did not want to add an automated test for the "create and buy" functionality, as this requires billing in order to succeed. I did, however, write a test program and verify that it worked:
```go
package main
import (
"encoding/json"
"flag"
"fmt"
"os"
"github.com/EasyPost/easypost-go"
)
func main() {
key := flag.String("api-key", "", "API key")
flag.Parse()
client := …
```

Properly Send Optional carrier_accounts Parameter When Creating Shipment 

---

README.md

👋 hello! I was looking for projects to learn a bit of go, and noticed this had easy install instructions, but then they were not working correctly!
This PR should fix the instructions, as `https://` doesn't work
cc @richshaffer or @bkeyoumarsi perhaps as contributors to the repo!

install instruction shouldnt say https://

---

.gitignore
examples/addresses/create_address.go
examples/addresses/retrieve_address.go
examples/addresses/retrieve_addresses.go
examples/batches/create_batch.go
examples/batches/retrieve_batch.go
examples/batches/retrieve_batches.go
examples/parcels/create_parcel.go
examples/parcels/retrieve_parcel.go
examples/scanforms/create_scanform.go
examples/scanforms/retrieve_scanform.go
examples/scanforms/retrieve_scanforms.go
examples/shipments/buy_shipment.go
examples/shipments/create_shipment.go
examples/shipments/retrieve_shipment.go
examples/shipments/retrieve_shipments.go

The Go library didn't have any examples like many of our other libraries. This PR adds various basic examples for objects like addresses, parcels, shipments, scanforms, and batches. Additionally, the example on the README threw various type errors so that example has been corrected in this PR too.

Added examples for various objects

---

.travis.yml
README.md
tests/batch_test.go

This closes #2 and adds some missing info to the README about how to run tests. Rates have also changed since last year so I tweaked a single unit test to allow those to pass again.
1. 2 variables will need to be added to the Travis CI backend: `TEST_API_KEY` and `PROD_API_KEY`. 
2. This repo will also need to be enabled via Travis CI if it isn't already.

Added Travis CI and added test info to README

---

CHANGELOG
address.go
batch.go
client.go
go.mod
go.sum
insurance.go
list_options.go
report.go
scan_form.go
shipment.go
tests/shipment_test.go
tests/testdata/TestClient/TestShipmentList.yaml
tracker.go
util.go
version.go

This change fixes the bug in forming of GET HTTP requests to fetch a list of objects with query params. 
- the bool query params set to `false` were ignored
- the query params were sent as `application/json` content-type in a GET request rather than the HTTP standard of `application/x-www-form-urlencoded`
The well established `github.com/google/go-querystring/query` pkg was added to simplify the implementation of this change.
A simple test has been added in `shipment_test.go` to verify this change.

Fix issue in performing list operations with query params

---

batch.go
examples/batches/scan_form_batch/scan_form_batch.go

This PR is intended to solve issue #11 raised by Justin Hammond.
Per EasyPost API Docs for creating a scan_form from a Batch object, the method should be a POST and not a GET.
docs link: https://www.easypost.com/docs/api#manifesting-scan-form
Rather than making a new method, I modified this existing method as I believe it was originally intended to do the thing we want to do.
`// GetBatchScanForms generates a scan form for the batch.`
I tested this method and indeed it failed as a GET request, as expected based on the API docs. Changing the method to a POST request resulted in successfully creating a scan_form using a batch id. 
renamed both methods `GetBatchScanForms` and `GetBatchScanFormsWithContext`
to be `CreateBatchScanForms` and `CreateBatchScanFormsWithContext` to follow …

Change 'GetBatchScanForms' to be 'CreateBatchScanForms'

---

rate.go
shipment.go
tests/shipment_test.go
tests/testdata/TestClient/TestShipmentSmartrates.yaml

Adds the new `/smartrate` endpoint/method on the `Shipment` object.
**NOTE:** Unlike our other client libraries using the Smartrate functionality, this will not return the `result` key but instead just the direct list of smartrates.
Simply call `GetShipmentSmartrates` and provide the shipment ID and you'll be returned a list of smartrates like so:
```json
[
{
"carrier": "USPS",
"carrier_account_id": "ca_123...",
"created_at": "2021-05-04T21:15:59Z",
"currency": "USD",
"delivery_date": null,
"delivery_date_guaranteed": true,
"delivery_days": null,
"est_delivery_days": null,
"id": "rate_123...",
"list_currency": null,
"list_rate": null,
"mode": "test",
"object": "Rate",
"rate": 0.01,
"retail_currency": null,
"retail_rate": null,
"service": "First",
"shipment_id": "shp_123", …
```

feat: adds smartrate functionality

---

shipment.go

This change prevents JSON decoding from failing when decoding an empty string for CODAmount

changed ShipmentOptions.CODAmount to string

---

CHANGELOG.md
version.go

Bumps version from 1.3.0 to 1.3.1
* Corrects `CODAmount` from a `float64` to a `string`

chore: version bump v1.3.1

---

CHANGELOG.md
tracker.go

This endpoint was introduced as an experiment in 2015 and never documented. It has no users and is being removed.

remove 2015-vintage experimental "all_updated" action on trackers

---

examples/shipments/rerate/rerate_shipment.go
shipment.go

Adds the missing `RerateShipment` function. Retrieving rates via `GetShipmentRates` only retrieves rates from the original shipment creation and does not get the current rates at the time of retrieval.
This PR follows the style of this repo and the pattern of our other client libraries. I added an example file and end to end tested it. Unit testing this particular endpoint is a bit obnoxious due to the 60 second timeout we impose between the creation of a shipment and its ability to be rerated. Running the example script produces output like the following:
```json
[
{
"id": "rate_123",
"object": "Rate",
"mode": "test",
"created_at": "2021-11-01T15:13:09Z",
"updated_at": "2021-11-01T15:13:09Z",
"service": "Priority",
"carrier": "UPSMailInnovations",
"carrier_account_id": "ca_123", …
```

feat: adds RerateShipment function

---

.github/workflows/ci.yml

Adds Go 1.16 and 1.17 to the matrix of go versions we test against.

chore: adds new go versions to test against on CI

---

CHANGELOG.md
order.go

Adds support to one-call buy an order by adding the missing `Service` field to the order object. You one-call buy an order just as you would a shipment, by passing the `service` you want to purchase and the `carrier_account` ID of the carrier it belongs to.
This was end-to-end tested to ensure it works properly.

feat: adds support to one-call buy an order

---

tracker.go

OriginLocation has a typo in the json field metadata which prevents this field from being populated on api calls.

Fix spelling error on json metadata

---

client.go
tests/client_test.go

Up until now, we have not provided a way for the user to set a custom timeout option for HTTP requests in our Go library.
This PR includes:
- A new `Timeout` property on the `Client` class, allowing the user to set a custom timeout for HTTP requests.
- `Timeout` defaults to 30 seconds if not set by user.
Due to using Go's built-in HTTP module, this timeout includes both the outgoing request and parsing the response.
Confirmed working by changing value and forcing timeouts during tests.

Add timeout option, default value for HTTP requests

---

CHANGELOG.md
shipment.go

This PR removes **GetShipmentRates()** and **GetShipmentRatesWithContext()** methods in the shipment file because the shipment struct already has rates, which makes this method unnecessary. If you need to get new rates for a shipment, please use the **RerateShipment()** method instead.

Remove get rate

---

.github/workflows/ci.yml
address.go
api_key.go
batch.go
carrier.go
customs.go
event.go
insurance.go
order.go
parcel.go
pickup.go
rate.go
report.go
scan_form.go
shipment.go
tests/batch_test.go
tests/insurance_test.go
tests/order_test.go
tests/pickup_test.go
tests/scan_form_test.go
tests/shipment_test.go
tests/testdata/TestClient/TestShipmentSmartrates.yaml
tests/tracker_test.go
tests/util_test.go
tracker.go
user.go
webhook.go

Lints the project on CI with `golangci-lint` to enforce it for future contributions. This is important because it was found that `golint` is deprecated and wasn't even catching linting errors on CI (see #41).
This tool includes:
- golint (via Staticcheck)
- gofmt
- go vet
- various other tools for Golang formatting/linting
Linting the project found the following:
- Various unused variables
- A misspelling of `omitempty` for the `TaxIdentifiers` object which is important because without it, we'd be populating an empty TaxIdentifiers object on all rate objects unintentionally
- And various other code cleanups including switching the `nil` context to `context.Background()` to signify it's meant to be an empty context.
I also had to introduce a new `SmartRate` struct because the `rate` fields …

chore: adds linting to CI

---

CHANGELOG.md
README.md
version.go

Prepares `v2.0.0` for release by updating the version and updating the CHANGELOG.

chore: prepare v2.0.0 for release

---

CHANGELOG.md
refund.go
tests/cassettes/TestAllRefund.yaml
tests/cassettes/TestCreateRefund.yaml
tests/cassettes/TestRefundAll.yaml
tests/cassettes/TestRefundCreate.yaml
tests/cassettes/TestRefundRetrieve.yaml
tests/cassettes/TestRetrieveRefund.yaml
tests/refund_test.go

This PR adds missing functions in Refund.
- Add `CreateRefund`, `CreateRefundWithContext`, `ListRefunds`, `ListRefundsWithContext`, `GetRefund`, and `GetRefundWithContext` in the Refund file

Add missing refund functions 

---

tests/batch_test.go
tests/cassettes/TestShipmentCreateWithIds.yaml
tests/shipment_test.go
tests/user_test.go

Adds a test when only IDs are passed to object creation. This was brought up as a way to check behavior across all libs due to: https://github.com/EasyPost/easypost-node/issues/222

chore: add shipment ID test

---

CHANGELOG.md
report.go
tests/cassettes/TestReportCustomAdditionalColumnsCreate.yaml
tests/cassettes/TestReportCustomColumnsCreate.yaml
tests/report_test.go

This PR:
- Adds support for specifying `Columns` and `AdditionalColumns` (both lists of strings) in parameters for the `CreateReport` function.
Unfortunately, since the API response does not indicate the columns used for a report, the only way to ensure the report actually includes the columns requested would be to make a live API call, download the generated CSV report and parse its column headers. That is a complex unit test with many points of failure and prevents us from using VCR.
Instead, we simply assume that if no error is thrown during the API call to generate and retrieve the report, that the report contains the correct columns. If it doesn't, that constitutes a server-side error that is out of our control.
This has been end-to-end tested locally. The generated report included …

[feat] Support for `columns` and `additional_columns` on Report creation

---

.github/workflows/ci.yml

This PR adds Go version 1.18 in the CI test

add Go version 1.18 in the CI test matrix.

---

CHANGELOG.md
customs.go

Customs Info struct is currently missing the `declaration` attribute.
This PR adds the `declaration` attribute in the Customs Info struct.

add declaration attribute in customs info struct.

---

.github/workflows/ci.yml
client.go
tests/address_test.go
tests/batch_test.go
tests/carrier_account_test.go
tests/cassettes/TestBatchCreateScanForm.yaml
tests/cassettes/TestBatchLabel.yaml
tests/customs_info_test.go
tests/customs_item_test.go
tests/event_test.go
tests/insurance_test.go
tests/order_test.go
tests/parcel_test.go
tests/pickup_test.go
tests/rate_test.go
tests/refund_test.go
tests/report_test.go
tests/scan_form_test.go
tests/shipment_test.go
tests/tracker_test.go
tests/user_test.go
tests/webhook_test.go

- Requires an API key before making a live API call
- Adds error checking into every test, otherwise a panic is thrown due to `test panicked: runtime error: invalid memory address or nil pointer dereference` when no API key is present for instance (this led to finding that one of the cassettes was recorded with errors and did not complete successfully. This should help debug Go tests moving forward much easier.)
- Adds dynamic wait periods for batch tests that require them based on the presence of the cassette

fix: require API key for requests

---

address.go
batch.go
carrier.go
customs.go
error.go
event.go
insurance.go
report.go
scan_form.go
shipment.go
tracker.go
webhook.go

Moves structs to the top of the file so they are all next to each other. Ensures structs appear first followed by functions for easier maintenance and grouping.
NA

refactor: consolidate struct location to top of files

---

README.md

We are about to launch our official Golang docs and as such, the link in the README needs to get updated.

fix: docs link in README to point to new official docs

---

CHANGELOG.md
tests/cassettes/TestWebhookAll.yaml
tests/cassettes/TestWebhookCreateWithSecret.yaml
tests/cassettes/TestWebhookDelete.yaml
tests/cassettes/TestWebhookRetrieve.yaml
tests/cassettes/TestWebhookUpdate.yaml
tests/cassettes/TestWebhookUpdateWithSecret.yaml
tests/fixture_test.go
tests/webhook_test.go
webhook.go

- Add support for webhook secrets when creating/updating a webhook
- `EnableWebhook` deprecated
- `CreateWebhook` deprecated
- New unit tests for secret testing
- Recorded new unit test cassettes
- All tests pass

Webhook secret

---

go.mod
go.sum
tests/fixture_test.go
tests/webhook_test.go
webhook.go

Adds a `ValidateWebhook` function that returns your webhook or raises an error if there is a `webhookSecret` mismatch
- Adds 3 tests to ensure that each branch (valid or invalid) works as intended

feat: adds a ValidateWebhook function

---

CHANGELOG.md
shipment.go
tests/shipment_test.go

- Add support for indicating an EndShipper ID when buying a shipment
- Add unit test for EndShipper ID when buying a shipment (disabled, E2E confirmed)
- E2E confirms that the `end_shipper_id` parameter in the JSON body was included and set correctly.

Include EndShipper ID when buying a shipment

---

.github/workflows/ci.yml
tests/bootstrap_test.go

Runs coverage on CI so we fail the build when coverage doesn't meet the criteria.
Drops the percentage by 3% due to reporting issues between CI and local.

fix: run coverage on CI to fail when under

---

referral.go
tests/billing_test.go
tests/bootstrap_test.go
tests/cassettes/TestReferralCustomerAddCreditCard.yaml
tests/referral_test.go

- Fix internal client-swapping for Stripe API calls to allow calls to be recorded
- Re-enable referral credit card unit test

Fix client swapping for Stripe API calls, re-enable referral credit card test

---

CHANGELOG.md
referral_customer.go
tests/cassettes/TestBetaReferralAddPaymentMethod.yaml
tests/referral_customer_test.go

Consolidates the `AddPaymentMethod` functions by removing the mistakenly included `BetaAddPaymentMethodWithPrimaryOrSecondary` and moving the `priority` param from there to the `BetaAddPaymentMethod` function since Go doesn't allow for default params, we needed to require it always. This is important because otherwise the naming is very confusing.
Updates tests and names.

fix: consolidate AddPaymentMethod functions

---

CHANGELOG.md
error.go
tests/error_test.go

Most of the time, the `message` property of an `APIError` object's JSON data is a string, but occasionally, our API sends something other than a string.
For example:
"message" is a JSON array
```
{
"error": {
...
"message": [
"ERROR 1",
"ERROR 2"
], 
...
}
```
"message" is a JSON dictionary
```
{
"error": {
...
"message": {
"errors": [
"ERROR 1",
"ERROR 2"
]
},
...
}
```
This PR enhances the JSON deserialization process for `APIError` objects to account for the "message" being an array, being a JSON dictionary, or being empty.
Shout out to @jchen293 who co-authored this but won't get credit.
- Unit tests updated to confirm logic works as expected

- Dynamically parse error message when generating a APIError object

---

.gitignore
Makefile

- [Reference the style guides](https://golangci-lint.run/usage/configuration/#command-line-options) from the examples submodule when formatting/linting (thankfully, no symlinking needed)
- Update Make steps, CI as needed to account for style guide imports
- Make steps work as expected locally

[chore] Import style guide from examples submodule

---

batch.go
tests/batch_test.go
tests/cassettes/TestBatchAddRemoveShipment.yaml

- `AddShipmentsToBatch` and `RemoveShipmentsFromBatch` now take explicit `Shipment` objects rather than interfaces.
- *BREAKING*: Users cannot pass in just shipment IDs, need to pass in whole shipment objects (see unit test updates for example)
- Fix internal logic that was building invalid JSON request schemas for add/remove shipment API calls
- Update unit tests to use whole shipment objects rather than IDs.

[fix] Add/remove shipments from batch now takes explicit Shipment objects

---

tracker.go

The API will soon only support providing a single tracking code as a filter when retrieving all Trackers, instead of a list of multiple tracking codes.
This PR changes the name and type restriction for the tracking code parameter in a `ListTrackerOptions` parameter set object, as well as internal storage logic for retrieving the next page of the paginated results.
This PR also updates the examples submodule to pull in the latest style guide.
- All unit tests pass
- Unit test passed with a new recording, but cassette does not need to be re-recorded as unit test does not use the tracking code parameter, meaning this change does not affect the cassette for the unit test.

[chore] Fix singular/plural TrackingCode(s) parameter discrepancy

---

CHANGELOG.md
constants.go

- FedEx SmartPost carrier account registration should hit `/register` endpoint for creation

[fix] FedEx SmartPost hits register endpoint

---

address.go
tests/address_test.go
tests/cassettes/TestAddressCreateAndVerify.yaml
tests/cassettes/TestAddressCreateVerify.yaml
tests/cassettes/TestAddressCreateVerifyStrict.yaml

See https://github.com/EasyPost/easypost-csharp/pull/540 for more details
- Update examples submodule
- Improve `TestAddressCreateAndVerify` to better test target functionality
- Unlike other libraries that will return the Address even if it is invalid from verification, due to how Go error checking works, the Address object is not returned, only the error.
- Update unit test, re-record cassettes as needed

[chore] Fix address verification unit test

---

CHANGELOG.md
payment_method.go
tests/billing_test.go

- Use payment method object type when determining type for fund, delete functions
- Update, add unit test to confirm "by object type" works to determine payment method type

[bug] Cannot determine payment method when funding/deleting

---

shipment_options.go

This PR adds fields used by [LaserShipV2](https://support.easypost.com/hc/en-us/articles/360062036932-Lasership-V2-Guide) carrier that were not previously present in the Go SDK. We are an existing customer of yours and have been using this custom patch in production to print LaserShip labels in non-trivial volumes for a while now.
Regression testing via existing unit tests (`make test`) all pass successfully with our own API keys, and we have manually validated LaserShipV2 labels that were printed, as well as validating the created `shipment` entities on EasyPost dashboard.

feat: add fields to shipment_options required by LaserShip

---

carrier.go

adds the missing `readable` and `logo` fields to `CarrierType`. Closes #221.

fix: add readable and logo fields to carrier type

---

CHANGELOG.md
Makefile
carrier.go
constants.go
error.go
tests/carrier_account_test.go
tests/cassettes/TestCarrierAccountCreateUps.yaml
tests/cassettes/TestCarrierAccountCreateWithCustomWorkflow.yaml
tests/cassettes/TestCarrierAccountUpdateUps.yaml

- Adds new `CreateUpsCarrierAccount` and `UpdateUpsCarrierAccount` methods and related parameter structs
- Add new `InvalidFunctionError`, raised if users attempt to mix UPS and non-UPS function calls and data
This is the least destructive path to integrating the completely-different payload schema for UPS accounts. Outside of the new error that will be raised if users attempt to mix UPS and non-UPS data, there are no breaking changes (compilation) introduced with this PR.
- New/updated unit tests for UPS and non-UPS creation/update functions
- Updated cassettes as needed

feat: Account for new UPS endpoint in carrier account create/update functions

---

CHANGELOG.md
claim.go
datetime.go
tests/cassettes/TestClaimAll.yaml
tests/cassettes/TestClaimCancel.yaml
tests/cassettes/TestClaimCreate.yaml
tests/cassettes/TestClaimGetNextPage.yaml
tests/cassettes/TestClaimRetrieve.yaml
tests/claim_test.go
tests/fixture_test.go

- Add claim-related functions: `CreateClaim`, `GetClaim`, `ListClaims`, `GetNextClaimPage` and `CancelClaim`
- Add unit tests, fixtures, cassettes as needed
- Add additional potential datetime format for parsing
- Added unit tests, fixtures and cassettes as needed

[feat] Add claims API service

---

tests/error_test.go

`ioutil.NopCloser` is deprecated, all it does under the hood is call `io.NopCloser` so I swapped the calls and tests still ran

fix: deprecated calls to ioutil.NopCloser

---

tests/error_test.go
tests/referral_customer_test.go

Per the docs, this new method of error comparison is preferred, let's follow best practice: https://pkg.go.dev/errors (bottom)

fix: use the newer preferred method for error comparison in tests

---

.github/workflows/ci.yml
Makefile
tests/fixture_test.go
tests/webhook_test.go

chore: update webhook validation fixtures

---

.github/workflows/ci.yml
Makefile
tests/bootstrap_test.go

I was playing with some Go items and found why we couldn't lint on Go 1.23, fixed via this PR. Also adds some helpful notes to the coveralls section if we can ever determine why it's failing to calculate on go 1.20

fix: linting on go 1.23

---

CHANGELOG.md
error.go
tests/address_test.go
tests/carrier_account_test.go
tests/cassettes/TestApiErrorAlternativeFormat.yaml
tests/error_test.go

- Fixes error parsing
- Allows for alternative format of `errors` field (previously we deserialized the `errors` field into a list of `Error` objects; however, sometimes the errors are simply a list of strings. This change makes the `errors` field an `interface`, allowing for either the renamed `FieldError` object or a list of strings. Users will need to check for the type of error returned and handle appropriately)
- Renamed the `Error` struct to `FieldError` to better match API docs and language
- Add alternative format test
- Add address verification error test

!fix: allow alternative error format
